### ISSUE TITLE
Compatiblity

### ISSUE THREAD

**Issue by zHawky** [Ted80-Minecraft-Mods/Realistic-World-Gen#13]
Man thanks for update, i tested some mods, so you can add in main thread
Gravestone
ChocoQuest
Ruins
Oceancraft (only kelps, looking for mobs)

but Mariculture is still not generate, i'll be waiting for rwg oceans :)

**Comment by ted80** [comment]
does the kelp spawn in rivers?

**Comment by zHawky** [comment]
not so frequently
