### ISSUE TITLE
Texture holes in RWG when using Underground Biomes Construct

### ISSUE THREAD

**Issue by Wytchcat** [Ted80-Minecraft-Mods/Realistic-World-Gen#2]
So when using UBC and RWG I get "holes" in stone areas... essentially see through blocks.  Only happens on stone or blocks next to stone.  

![rwg_caveworld](https://cloud.githubusercontent.com/assets/3827194/5842555/9b07ae68-a15a-11e4-8fd6-78ed813fbfee.jpg)

Thanks!

**Comment by ted80** [comment]
the Underground Biomes Construct mod doesn't change the metadata back to 0 when replacing a block.

**Comment by Wytchcat** [comment]
Gotcha, thanks
