### ISSUE TITLE
[Shot trouble, issue not with RWG] AM2 worldgen conflict solved

### ISSUE THREAD

**Issue by xenoswift** [Ted80-Minecraft-Mods/Realistic-World-Gen#26]
Heyo,

I have two instances that run with Ars Magica 2, the older runs with ATG and as worldgen with EXBL. The newer runs with RWG and EXBL.
AM2 features generate properly and as expected (in similar distribution to Thaumcraft ores) with ATG but do not generate at all with RWG. In certain biomes, AM2 mob spawning is affected as well, with hardly any of its monsters spawning at night or Dryads in the day.

The issue doesn't exist with ATG+EXBL but exists with RWG+EXBL so this all leads me to believe there's something wrong with RWG as it is the uncommon factor between the two. If anyone else has experience with this same issue and has found a workaround I would appreciate it if you shared your steps.

(As an aside, AM2's regeneration did not work)

**Comment by xenoswift** [comment]
Narrowed the issue from RWG to something else. Recurrent Complex must be at fault as the rest of the modlist is unchanged.

**Comment by Razorskills** [comment]
ATG? there is a mod called Alternative terrain generation.. But this one is called RTG.. Realism terrain generation.

Which one are you using?

**Comment by xenoswift** [comment]
Problem was solved, forgot to close the issue, my bad.
