### ISSUE TITLE
Client crashes but the server stays running

### ISSUE THREAD

**Issue by misterfixit** [Ted80-Minecraft-Mods/Realistic-World-Gen#5]
https://www.dropbox.com/s/c9fpfd1ywm1mkew/crash-2015-02-23_22.58.58-client.txt?dl=0

**Comment by ted80** [comment]
this error is not caused by rwg

**Comment by misterfixit** [comment]
yeah I just got the crash without rwg, apologies for the false report. Any ideas what is causing this?

**Comment by ted80** [comment]
it has something to do with AI

**Comment by Lanse505** [comment]
Its currently under investigation, it's some random mod causing a wierd NBT-call between server and client, which forces the Client to create a null NBT tag with a invalid Default value thats then causing a crash :/. Its a mod essentially stiring up a bug in Base Minecrafts code.
