### ISSUE TITLE
Biomes O Plenty config support

### ISSUE THREAD

**Issue by Qohelethh** [Ted80-Minecraft-Mods/Realistic-World-Gen#9]
Currently, RWG generates all BOP biomes regardless of what biomes are disabled in the BOP config file. It would be a lot better if you could disable specific biomes to prevent them from generating.

**Comment by ted80** [comment]
I can't get biome weight and disable settings from the biomes 'o plenty api

**Comment by Qohelethh** [comment]
Could you add a config setting of your own to determine which biomes spawn?
